version: '3.5'
services:
    connectors:
        image: connectors:tag
        build: ./docker
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - ${DEV_IP}:8080:8080
        environment:
            # Envs for tests are load from .jest/testEnvs.js
            JEST_DOCKER: 1
            APP_ENV: 'debug'
            BACKEND_URL: https://${DEV_IP}
            STARTING_POINT_URL: 'https://sp.orchesty.com'
            WORKER_API_HOST: https://${DEV_IP}
            CRYPT_SECRET: 'ThisIsNotSoSecret'
        command: sleep infinity

    redis:
        image: redis:alpine
        ports:
            - ${DEV_IP}:6379:6379

    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - ${DEV_IP}:15672:15672
            - ${DEV_IP}:5672:5672
