packages:
  - "lib/*"
  - "lib/AmazonApps/*"
  - "lib/Google/*"

catalog:
  eslint: ^10.11.0

overrides:
  eslint: "catalog:"

allowBuilds:
  '@parcel/watcher': false
  oracledb: false
  protobufjs: false
  unrs-resolver: true

yes: true